server:
  port: 9011
spring:
  application:
    name: manager
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    register:
      path: /register/**
      serviceId: register